### ISSUE TITLE
Errors in patch 11.0.2

### ISSUE THREAD

**Issue by AutolycusWolf** [millanzarreta/GreyOnCooldown#3]
Keep getting the following error as of the latest patch (11.0.2 The War Within)

10x GreyOnCooldown/GreyOnCooldown.lua:336: attempt to call global 'GetSpellCooldown' (a nil value)
[string "@GreyOnCooldown/GreyOnCooldown.lua"]:336: in function <GreyOnCooldown/GreyOnCooldown.lua:318>
[string "=[C]"]: in function `ActionButton_UpdateCooldown'
[string "@Blizzard_ActionBar/Mainline/SpellFlyout.lua"]:85: in function `SpellFlyoutButton_UpdateCooldown'
[string "@Blizzard_ActionBar/Mainline/SpellFlyout.lua"]:303: in function `Toggle'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:339: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function `SecureActionButton_OnClick'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:1438: in function <Blizzard_ActionBar/Mainline/ActionButton.lua:1408>
[string "=[C]"]: ?

Locals:
self = SpellFlyoutButton1 {
 FlyoutArrowContainer = Frame {
 }
 NewActionTexture = Texture {
 }
 LevelLinkLockIcon = Texture {
 }
 Flash = SpellFlyoutButton1Flash {
 }
 GlyphTranslation = Texture {
 }
 TargetReticleAnimFrame = Frame {
 }
 icon = SpellFlyoutButton1Icon {
 }
 SlotArt = Texture {
 }
 AbilityHighlight = Texture {
 }
 InterruptDisplay = Frame {
 }
 GlyphActivateAnim = AnimationGroup {
 }
 spellID = 1462
 HotKey = SpellFlyoutButton1HotKey {
 }
 HighlightTexture = Texture {
 }
 GlyphIcon = Texture {
 }
 spellName = "Beast Lore"
 CooldownFlash = Frame {
 }
 IconMask = MaskTexture {
 }
 TextOverlayContainer = Frame {
 }
 AbilityHighlightAnim = AnimationGroup {
 }
 maxDisplayCount = 99
 GlyphActivate = Texture {
 }
 FlyoutBorderShadow = SpellFlyoutButton1FlyoutBorderShadow {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 CheckedTexture = Texture {
 }
 Border = SpellFlyoutButton1Border {
 }
 SpellHighlightTexture = Texture {
 }
 PushedTexture = Texture {
 }
 NormalTexture = SpellFlyoutButton1NormalTexture {
 }
 Name = SpellFlyoutButton1Name {
 }
 SpellCastAnimFrame = Frame {
 }
 SlotBackground = Texture {
 }
 AutoCastOverlay = Frame {
 }
 cooldown = SpellFlyoutButton1Cooldown {
 }
 Count = SpellFlyoutButton1Count {
 }
}
expectedUpdate = nil
icon = SpellFlyoutButton1Icon {
}
spellID = 1462
action = nil
start = nil
duration = nil
(*temporary) = nil
(*temporary) = 1462
(*temporary) = "attempt to call global 'GetSpellCooldown' (a nil value)"
UpdateFuncCache = <table> {
}

**Comment by millanzarreta** [comment]
Fixed in the new version. Ty for the report.
